[package]
name = "ptv-forms"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Benedikt Claus"]
license = "MIT"
description = "Forms for German psychotherapy application"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"